### ISSUE TITLE
LBL FastDERMS file path error

### ISSUE THREAD

**Issue by AAndersn** [GRIDAPPSD/gridappsd-forum#126]
@MaximeBaudette There is an issue with the file path in io13gapps.py identified by me and @jsmacdonald 

Please update us when this is fixed and we can do a git pull. 

```
ERROR:FAST_DERMS_CONTROL.IOs.IOgapps:'str' object has no attribute 'absolute'
ERROR:FAST_DERMS_CONTROL.IOs.IOgapps:Failed to fetch model _C07972A7-600D-4AA5-B254-4CAA4263560E through gridappsd
ERROR:__Main__Orchastrator:local variable 'import_result' referenced before assignment
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/ubuntu/FRS_SIM/fastderms/src/FAST_DERMS_CONTROL/IOs/IO13gapps.py", line 14, in fetch_model
    return super(IO13gapps, self).fetch_model(model_id)
  File "/home/ubuntu/FRS_SIM/fastderms/src/FAST_DERMS_CONTROL/IOs/IOgapps.py", line 113, in fetch_model
    return super().fetch_model(response)
  File "/home/ubuntu/FRS_SIM/fastderms/src/FAST_DERMS_CONTROL/IOs/IOclass.py", line 422, in fetch_model
    return super().fetch_model(str(path_to_model.absolute()))
AttributeError: 'str' object has no attribute 'absolute'
```

**Comment by AAndersn** [comment]
Resolved
