### ISSUE TITLE
Error when running simulation with sensor service

### ISSUE THREAD

**Issue by blthayer** [GRIDAPPSD/gridappsd-forum#38]
@poorva1209 @craig8 
Platform version: `v2019.10.0`

Simulation configuration is below. Note you'll need to change the "applications" section to be an empty list (or switch it to use the sample app).
```
{
  "power_system_config": {
    "GeographicalRegion_name": "_73C512BD-7249-4F50-50DA-D93849B89C43",
    "SubGeographicalRegion_name": "_A1170111-942A-6ABD-D325-C64886DC4D7D",
    "Line_name": "_AAE94E4A-2465-6F5E-37B1-3E72183A4E44"
  },
  "application_config": {
    "applications": [
      {
        "name": "PyVVO"
      }
    ]
  },
  "simulation_config": {
    "start_time": "1358121600",
    "duration": "300",
    "simulator": "GridLAB-D",
    "timestep_frequency": "1000",
    "timestep_increment": "1000",
    "run_realtime": false,
    "simulation_name": "ieee8500",
    "power_flow_solver_method": "NR",
    "model_creation_config": {
      "load_scaling_factor": "1",
      "schedule_name": "ieeezipload",
      "z_fraction": "0",
      "i_fraction": "1",
      "p_fraction": "0",
      "randomize_zipload_fractions": false,
      "use_houses": false
    }
  },
  "test_config": {
    "events": [],
    "appId": "_AAE94E4A-2465-6F5E-37B1-3E72183A4E44"
  },
  "service_configs": [
    {
      "id": "gridappsd-sensor-simulator",
      "user_options": {
        "sensors-config": {
          "_cd29cea1-8517-4a44-89f0-1a91042830a1": {
            "nominal-value": 120,
            "perunit-confidence-band": 0.01,
            "aggregation-interval": 30,
            "perunit-drop-rate": 0
          },
          "_17593302-8b33-4fd4-b853-d83eabbb522e": {
            "nominal-value": 120,
            "perunit-confidence-band": 0.01,
            "aggregation-interval": 30,
            "perunit-drop-rate": 0
          },
          "_d34e9c1d-84c6-40cb-829d-14576db951ca": {
            "nominal-value": 120,
            "perunit-confidence-band": 0.01,
            "aggregation-interval": 30,
            "perunit-drop-rate": 0
          },
          "_04f69915-92ec-4116-bccb-8fe0a5f4eea9": {
            "nominal-value": 120,
            "perunit-confidence-band": 0.01,
            "aggregation-interval": 30,
            "perunit-drop-rate": 0
          }
        },
        "random-seed": 42,
        "default-aggregation-interval": 30,
        "passthrough-if-not-specified": false,
        "default-perunit-confidence-band": 0.01,
        "default-perunit-drop-rate": 0
      }
    }
  ]
}
```

Platform error:
```
New ProcessEvents
LOOKING FOR CONVERTER PROVEN_WEATHER:GRIDLABD_WEATHER  IN   {PROVEN_LOADPROFILE:GRIDLABD_LOAD_SCHEDULE=gov.pnnl.goss.gridappsd.data.conversion.ProvenLoadScheduleToGridlabdLoadScheduleConverter@20117281, PROVEN_WEATHER:GRIDLABD_WEATHER=gov.pnnl.goss.gridappsd.data.conversion.ProvenWeatherToGridlabdWeatherConverter@553f467c}
LOOKING FOR CONVERTER PROVEN_LOADPROFILE:GRIDLABD_LOAD_SCHEDULE  IN   {PROVEN_LOADPROFILE:GRIDLABD_LOAD_SCHEDULE=gov.pnnl.goss.gridappsd.data.conversion.ProvenLoadScheduleToGridlabdLoadScheduleConverter@20117281, PROVEN_WEATHER:GRIDLABD_WEATHER=gov.pnnl.goss.gridappsd.data.conversion.ProvenWeatherToGridlabdWeatherConverter@553f467c}
WATCHING gridappsd-sensor-simulator-1571948115738
java.lang.RuntimeException: Service not found: 
	at gov.pnnl.goss.gridappsd.service.ServiceManagerImpl.startServiceForSimultion(ServiceManagerImpl.java:260)
	at gov.pnnl.goss.gridappsd.process.ProcessNewSimulationRequest.process(ProcessNewSimulationRequest.java:292)
	at gov.pnnl.goss.gridappsd.process.ProcessEvent.onMessage(ProcessEvent.java:176)
	at pnnl.goss.core.client.GossClient$1.run(GossClient.java:321)
	at java.lang.Thread.run(Thread.java:748)
Thread-42 ERROR [gov.pnnl.goss.gridappsd.log.LogManagerImpl] - 1571948115758|gov.pnnl.goss.gridappsd.process.ProcessNewSimulationRequest|1845212299|ERROR|system|ERROR
Process Initialization error: Service not found: 

Thread-39 ERROR [gov.pnnl.goss.gridappsd.log.LogManagerImpl] - 1571948115758|gov.pnnl.goss.gridappsd.process.ProcessNewSimulationRequest|1845212299|ERROR|system|ERROR
Process Initialization error: Service not found: 
```

**Comment by blthayer** [comment]
@poorva1209 @craig8 - I had a bad configuration for my application - had the empty string in prereqs.
